resources:
  - name: every-hour-resource
    type: time
    icon: clock-outline
    source:
      interval: 1h
  - name: concourse-base-image-docker-hub
    type: registry-image
    source:
      username: ((dockerhub_username))
      password: ((dockerhub_password))
      repository: gdscyber/cyber-security-concourse-base-image


jobs:
  - name: scan-cyber-base-image
    serial: true
    plan:
      - get: concourse-base-image-docker-hub
        params:
          format: oci # Fetch image as a tarball for trivy's --input option
      - get: every-hour-resource
        trigger: true
      - task: scan for CRITICAL severity vulnerabilities
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: aquasec/trivy}
          inputs:
            - name: concourse-base-image-docker-hub
          run:
            path: trivy
            args:
              - --light
              - --ignore-unfixed # Ignores vulns that can't be fixed by updating package
              # This might miss severe vulnerabilities!
              - --quiet
              - --exit-code
              - 1
              - --severity
              - CRITICAL 
              - --input
              - concourse-base-image-docker-hub/image.tar
          #params:
          #  TRIVY_AUTH_URL: 'https://registry.hub.docker.com'
          #  TRIVY_USERNAME: ((dockerhub_username))
          #  TRIVY_PASSWORD: ((dockerhub_password))
