resources:
  - name: concourse-base-image-git
    type: git
    source:
      branch: master
      uri: https://github.com/alphagov/cyber-security-concourse-base-image.git

  - name: load-testing-image-git
    type: git
    source:
      branch: master
      paths:
        - load_testing
      uri: https://github.com/alphagov/cyber-security-concourse-base-image.git

  - name: concourse-base-image-docker-hub
    type: registry-image
    source: &build-image-source
      username: ((dockerhub_username))
      password: ((dockerhub_password))
      repository: gdscyber/cyber-security-concourse-base-image

  - name: load-testing-image-docker-hub
    type: registry-image
    source:
      <<: *build-image-source
      repository: gdscyber/artillery-load-testing

jobs:
  - name: build_base_docker_image
    serial: false
    plan:
    - get: concourse-base-image-git
      trigger: true

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: concourse-base-image-git/
        inputs:
        - name: concourse-base-image-git
        outputs:
        - name: image
        run:
          path: build

    - put: concourse-base-image-docker-hub
      params:
        image: image/image.tar


  - name: build_load_testing_docker_image
    serial: false
    plan:
    - get: load-testing-image-git
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: load-testing-image-git/load_tesing
        inputs:
        - name: load-testing-image-git
        outputs:
        - name: image
        run:
          path: build

    - put: load-testing-image-docker-hub
      params:
        image: image/image.tar
